spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop
    username: root
    password: 1q2w3e4r5
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

server:
  port: 8080